name: "Merge on lgtm label"
on:
  pull_request:

jobs:
  label-check:
    runs-on: ubuntu-latest
    steps:
      - uses: NathanielHill/check-pr-label-action@v4.0.0
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          valid-labels: 'lgtm'

  build:
    name: build
    runs-on: ubuntu-latest
    needs:
      # make sure all required jobs are listed here
      - label-check
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: fmt
        run: IS_CONTAINER=yes make fmt

      - name: Build
        run: make all

  test:
    name: test
    runs-on: ubuntu-latest
    needs:
      # make sure all required jobs are listed here
      - label-check
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: test pkg
        run: make test-pkg

      - name: test controllers on opensfhit
        run: CLUSTER_TYPE=openshift make test-controllers

  mergepal-merge: # run merge pal in the end
    runs-on: ubuntu-latest
    needs:
      # make sure all required jobs are listed here
      - label-check
      - test
      - build
    steps:
      - uses: actions/checkout@v1
      - uses: maxkomarychev/merge-pal-action@v0.5.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
