name: Merge Bot

on:
  workflow_run:
    workflows: ["Prow github actions"]
    types:
      - completed

jobs:
  merge:
    runs-on: ubuntu-latest
    name: Merge
    steps:
      - name: Integration check
        uses: squalrus/merge-bot@v0.4.3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          test: true
          reviewers: false
          labels: lgtm
          blocking_labels: hold
          checks_enabled: false
          method: merge
          delete_source_branch: false
